# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../learning_pyqt/second_test/print_fucker.ui'
#
# Created: Wed Oct 15 01:35:40 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1920, 1032)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.main_menu_tabs = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_tabs.sizePolicy().hasHeightForWidth())
        self.main_menu_tabs.setSizePolicy(sizePolicy)
        self.main_menu_tabs.setMinimumSize(QtCore.QSize(0, 0))
        self.main_menu_tabs.setTabPosition(QtGui.QTabWidget.North)
        self.main_menu_tabs.setIconSize(QtCore.QSize(16, 16))
        self.main_menu_tabs.setObjectName(_fromUtf8("main_menu_tabs"))
        self.add_inventory_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_inventory_tab.sizePolicy().hasHeightForWidth())
        self.add_inventory_tab.setSizePolicy(sizePolicy)
        self.add_inventory_tab.setObjectName(_fromUtf8("add_inventory_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.add_inventory_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.add_item_lbl = QtGui.QLabel(self.add_inventory_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(18)
        self.add_item_lbl.setFont(font)
        self.add_item_lbl.setScaledContents(False)
        self.add_item_lbl.setObjectName(_fromUtf8("add_item_lbl"))
        self.horizontalLayout_2.addWidget(self.add_item_lbl)
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_item_vert_line = QtGui.QFrame(self.add_inventory_tab)
        self.add_item_vert_line.setFrameShape(QtGui.QFrame.VLine)
        self.add_item_vert_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.add_item_vert_line.setObjectName(_fromUtf8("add_item_vert_line"))
        self.horizontalLayout_2.addWidget(self.add_item_vert_line)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.search_upc_box = QtGui.QLineEdit(self.add_inventory_tab)
        self.search_upc_box.setObjectName(_fromUtf8("search_upc_box"))
        self.horizontalLayout_2.addWidget(self.search_upc_box)
        self.search_upc_button = QtGui.QPushButton(self.add_inventory_tab)
        self.search_upc_button.setObjectName(_fromUtf8("search_upc_button"))
        self.horizontalLayout_2.addWidget(self.search_upc_button)
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.add_item_vert_line_2 = QtGui.QFrame(self.add_inventory_tab)
        self.add_item_vert_line_2.setFrameShape(QtGui.QFrame.VLine)
        self.add_item_vert_line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.add_item_vert_line_2.setObjectName(_fromUtf8("add_item_vert_line_2"))
        self.horizontalLayout_2.addWidget(self.add_item_vert_line_2)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.search_artist_box = QtGui.QLineEdit(self.add_inventory_tab)
        self.search_artist_box.setText(_fromUtf8(""))
        self.search_artist_box.setObjectName(_fromUtf8("search_artist_box"))
        self.horizontalLayout_2.addWidget(self.search_artist_box)
        self.search_artist_button = QtGui.QPushButton(self.add_inventory_tab)
        self.search_artist_button.setObjectName(_fromUtf8("search_artist_button"))
        self.horizontalLayout_2.addWidget(self.search_artist_button)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.add_item_vert_line_3 = QtGui.QFrame(self.add_inventory_tab)
        self.add_item_vert_line_3.setFrameShape(QtGui.QFrame.VLine)
        self.add_item_vert_line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.add_item_vert_line_3.setObjectName(_fromUtf8("add_item_vert_line_3"))
        self.horizontalLayout_2.addWidget(self.add_item_vert_line_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.search_artist_box_2 = QtGui.QLineEdit(self.add_inventory_tab)
        self.search_artist_box_2.setText(_fromUtf8(""))
        self.search_artist_box_2.setObjectName(_fromUtf8("search_artist_box_2"))
        self.horizontalLayout_2.addWidget(self.search_artist_box_2)
        self.search_artist_box_3 = QtGui.QLineEdit(self.add_inventory_tab)
        self.search_artist_box_3.setText(_fromUtf8(""))
        self.search_artist_box_3.setObjectName(_fromUtf8("search_artist_box_3"))
        self.horizontalLayout_2.addWidget(self.search_artist_box_3)
        self.search_artist_button_2 = QtGui.QPushButton(self.add_inventory_tab)
        self.search_artist_button_2.setObjectName(_fromUtf8("search_artist_button_2"))
        self.horizontalLayout_2.addWidget(self.search_artist_button_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.results_table = QtGui.QTableWidget(self.add_inventory_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_table.sizePolicy().hasHeightForWidth())
        self.results_table.setSizePolicy(sizePolicy)
        self.results_table.setMinimumSize(QtCore.QSize(1850, 400))
        self.results_table.setObjectName(_fromUtf8("results_table"))
        self.results_table.setColumnCount(19)
        self.results_table.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.results_table.setItem(0, 2, item)
        self.results_table.horizontalHeader().setCascadingSectionResizes(False)
        self.results_table.horizontalHeader().setDefaultSectionSize(100)
        self.results_table.horizontalHeader().setSortIndicatorShown(False)
        self.results_table.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.results_table)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.add_item_lbl_3 = QtGui.QLabel(self.add_inventory_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(18)
        self.add_item_lbl_3.setFont(font)
        self.add_item_lbl_3.setScaledContents(False)
        self.add_item_lbl_3.setObjectName(_fromUtf8("add_item_lbl_3"))
        self.horizontalLayout_3.addWidget(self.add_item_lbl_3)
        spacerItem6 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.add_item_vert_line_7 = QtGui.QFrame(self.add_inventory_tab)
        self.add_item_vert_line_7.setFrameShape(QtGui.QFrame.VLine)
        self.add_item_vert_line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.add_item_vert_line_7.setObjectName(_fromUtf8("add_item_vert_line_7"))
        self.horizontalLayout_3.addWidget(self.add_item_vert_line_7)
        spacerItem7 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.add_to_inventory_button = QtGui.QPushButton(self.add_inventory_tab)
        self.add_to_inventory_button.setObjectName(_fromUtf8("add_to_inventory_button"))
        self.horizontalLayout_3.addWidget(self.add_to_inventory_button)
        self.print_check_box = QtGui.QCheckBox(self.add_inventory_tab)
        self.print_check_box.setChecked(True)
        self.print_check_box.setObjectName(_fromUtf8("print_check_box"))
        self.horizontalLayout_3.addWidget(self.print_check_box)
        spacerItem8 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.add_item_vert_line_8 = QtGui.QFrame(self.add_inventory_tab)
        self.add_item_vert_line_8.setFrameShape(QtGui.QFrame.VLine)
        self.add_item_vert_line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.add_item_vert_line_8.setObjectName(_fromUtf8("add_item_vert_line_8"))
        self.horizontalLayout_3.addWidget(self.add_item_vert_line_8)
        spacerItem9 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.generate_sku_button = QtGui.QPushButton(self.add_inventory_tab)
        self.generate_sku_button.setObjectName(_fromUtf8("generate_sku_button"))
        self.horizontalLayout_3.addWidget(self.generate_sku_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.add_inventory_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(24)
        font.setItalic(True)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.add_item_lbl_4 = QtGui.QLabel(self.add_inventory_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(18)
        self.add_item_lbl_4.setFont(font)
        self.add_item_lbl_4.setScaledContents(False)
        self.add_item_lbl_4.setObjectName(_fromUtf8("add_item_lbl_4"))
        self.horizontalLayout_4.addWidget(self.add_item_lbl_4)
        spacerItem10 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.add_item_vert_line_9 = QtGui.QFrame(self.add_inventory_tab)
        self.add_item_vert_line_9.setFrameShape(QtGui.QFrame.VLine)
        self.add_item_vert_line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.add_item_vert_line_9.setObjectName(_fromUtf8("add_item_vert_line_9"))
        self.horizontalLayout_4.addWidget(self.add_item_vert_line_9)
        spacerItem11 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.add_to_inventory_button_3 = QtGui.QPushButton(self.add_inventory_tab)
        self.add_to_inventory_button_3.setObjectName(_fromUtf8("add_to_inventory_button_3"))
        self.horizontalLayout_4.addWidget(self.add_to_inventory_button_3)
        self.add_to_inventory_button_4 = QtGui.QPushButton(self.add_inventory_tab)
        self.add_to_inventory_button_4.setObjectName(_fromUtf8("add_to_inventory_button_4"))
        self.horizontalLayout_4.addWidget(self.add_to_inventory_button_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.add_item_lbl_5 = QtGui.QLabel(self.add_inventory_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(18)
        self.add_item_lbl_5.setFont(font)
        self.add_item_lbl_5.setScaledContents(False)
        self.add_item_lbl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.add_item_lbl_5.setObjectName(_fromUtf8("add_item_lbl_5"))
        self.gridLayout.addWidget(self.add_item_lbl_5, 0, 1, 1, 1)
        self.just_added_table = QtGui.QTableWidget(self.add_inventory_tab)
        self.just_added_table.setMinimumSize(QtCore.QSize(900, 375))
        self.just_added_table.setObjectName(_fromUtf8("just_added_table"))
        self.just_added_table.setColumnCount(19)
        self.just_added_table.setRowCount(19)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.just_added_table.setItem(0, 0, item)
        self.gridLayout.addWidget(self.just_added_table, 1, 0, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.add_inventory_tab)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout.addWidget(self.textBrowser, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.main_menu_tabs.addTab(self.add_inventory_tab, _fromUtf8(""))
        self.search_inventory_tab = QtGui.QWidget()
        self.search_inventory_tab.setObjectName(_fromUtf8("search_inventory_tab"))
        self.main_menu_tabs.addTab(self.search_inventory_tab, _fromUtf8(""))
        self.check_out_tab = QtGui.QWidget()
        self.check_out_tab.setObjectName(_fromUtf8("check_out_tab"))
        self.main_menu_tabs.addTab(self.check_out_tab, _fromUtf8(""))
        self.history_tab = QtGui.QWidget()
        self.history_tab.setObjectName(_fromUtf8("history_tab"))
        self.main_menu_tabs.addTab(self.history_tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.main_menu_tabs)

        self.retranslateUi(Form)
        self.main_menu_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Plaid Room Records", None))
        self.add_item_lbl.setText(_translate("Form", "Search Item", None))
        self.search_upc_button.setText(_translate("Form", "Search UPC/SKU/EAN", None))
        self.search_artist_button.setText(_translate("Form", "Search Artist", None))
        self.search_artist_button_2.setText(_translate("Form", "Search Artist/Title", None))
        item = self.results_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.results_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.results_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.results_table.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.results_table.verticalHeaderItem(4)
        item.setText(_translate("Form", "5", None))
        item = self.results_table.verticalHeaderItem(5)
        item.setText(_translate("Form", "6", None))
        item = self.results_table.verticalHeaderItem(6)
        item.setText(_translate("Form", "7", None))
        item = self.results_table.verticalHeaderItem(7)
        item.setText(_translate("Form", "8", None))
        item = self.results_table.verticalHeaderItem(8)
        item.setText(_translate("Form", "9", None))
        item = self.results_table.verticalHeaderItem(9)
        item.setText(_translate("Form", "10", None))
        item = self.results_table.verticalHeaderItem(10)
        item.setText(_translate("Form", "11", None))
        item = self.results_table.verticalHeaderItem(11)
        item.setText(_translate("Form", "12", None))
        item = self.results_table.verticalHeaderItem(12)
        item.setText(_translate("Form", "13", None))
        item = self.results_table.verticalHeaderItem(13)
        item.setText(_translate("Form", "14", None))
        item = self.results_table.verticalHeaderItem(14)
        item.setText(_translate("Form", "15", None))
        item = self.results_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "UPC/SKU/EAN", None))
        item = self.results_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Artist", None))
        item = self.results_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Title", None))
        item = self.results_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Sale Price", None))
        item = self.results_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Format", None))
        item = self.results_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Label", None))
        item = self.results_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Genre", None))
        item = self.results_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "New/Used", None))
        item = self.results_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Year", None))
        item = self.results_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Distributor", None))
        item = self.results_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Date Added", None))
        item = self.results_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Price Paid", None))
        item = self.results_table.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Real Name", None))
        item = self.results_table.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Profile", None))
        item = self.results_table.horizontalHeaderItem(14)
        item.setText(_translate("Form", "Variations", None))
        item = self.results_table.horizontalHeaderItem(15)
        item.setText(_translate("Form", "Aliases", None))
        item = self.results_table.horizontalHeaderItem(16)
        item.setText(_translate("Form", "Discogs Release Number", None))
        item = self.results_table.horizontalHeaderItem(17)
        item.setText(_translate("Form", "Track List", None))
        item = self.results_table.horizontalHeaderItem(18)
        item.setText(_translate("Form", "Notes", None))
        __sortingEnabled = self.results_table.isSortingEnabled()
        self.results_table.setSortingEnabled(False)
        self.results_table.setSortingEnabled(__sortingEnabled)
        self.add_item_lbl_3.setText(_translate("Form", "Add Item", None))
        self.add_to_inventory_button.setText(_translate("Form", "Add Selected Item To Inventory", None))
        self.print_check_box.setText(_translate("Form", "Print Sticker", None))
        self.generate_sku_button.setText(_translate("Form", "Generate New SKU For Selected Item", None))
        self.add_item_lbl_4.setText(_translate("Form", "Recent Additions", None))
        self.add_to_inventory_button_3.setText(_translate("Form", "Remove Selected Item From Inventory", None))
        self.add_to_inventory_button_4.setText(_translate("Form", "Edit Selected Item", None))
        self.add_item_lbl_5.setText(_translate("Form", "Console", None))
        item = self.just_added_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.just_added_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.just_added_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.just_added_table.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.just_added_table.verticalHeaderItem(4)
        item.setText(_translate("Form", "5", None))
        item = self.just_added_table.verticalHeaderItem(5)
        item.setText(_translate("Form", "6", None))
        item = self.just_added_table.verticalHeaderItem(6)
        item.setText(_translate("Form", "7", None))
        item = self.just_added_table.verticalHeaderItem(7)
        item.setText(_translate("Form", "8", None))
        item = self.just_added_table.verticalHeaderItem(8)
        item.setText(_translate("Form", "9", None))
        item = self.just_added_table.verticalHeaderItem(9)
        item.setText(_translate("Form", "10", None))
        item = self.just_added_table.verticalHeaderItem(10)
        item.setText(_translate("Form", "11", None))
        item = self.just_added_table.verticalHeaderItem(11)
        item.setText(_translate("Form", "12", None))
        item = self.just_added_table.verticalHeaderItem(12)
        item.setText(_translate("Form", "13", None))
        item = self.just_added_table.verticalHeaderItem(13)
        item.setText(_translate("Form", "14", None))
        item = self.just_added_table.verticalHeaderItem(14)
        item.setText(_translate("Form", "15", None))
        item = self.just_added_table.verticalHeaderItem(15)
        item.setText(_translate("Form", "16", None))
        item = self.just_added_table.verticalHeaderItem(16)
        item.setText(_translate("Form", "17", None))
        item = self.just_added_table.verticalHeaderItem(17)
        item.setText(_translate("Form", "18", None))
        item = self.just_added_table.verticalHeaderItem(18)
        item.setText(_translate("Form", "20", None))
        item = self.just_added_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "UPC/SKU/EAN", None))
        item = self.just_added_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Title", None))
        item = self.just_added_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column", None))
        item = self.just_added_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Sale Price", None))
        item = self.just_added_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Format", None))
        item = self.just_added_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Label", None))
        item = self.just_added_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Genre", None))
        item = self.just_added_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "New Column", None))
        item = self.just_added_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "New/Used", None))
        item = self.just_added_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Year", None))
        item = self.just_added_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Distributor", None))
        item = self.just_added_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Date Added", None))
        item = self.just_added_table.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Real Name", None))
        item = self.just_added_table.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Profile", None))
        item = self.just_added_table.horizontalHeaderItem(14)
        item.setText(_translate("Form", "New Column", None))
        item = self.just_added_table.horizontalHeaderItem(15)
        item.setText(_translate("Form", "Variations", None))
        item = self.just_added_table.horizontalHeaderItem(16)
        item.setText(_translate("Form", "Discogs Release Number", None))
        item = self.just_added_table.horizontalHeaderItem(17)
        item.setText(_translate("Form", "New Column", None))
        item = self.just_added_table.horizontalHeaderItem(18)
        item.setText(_translate("Form", "Notes", None))
        __sortingEnabled = self.just_added_table.isSortingEnabled()
        self.just_added_table.setSortingEnabled(False)
        self.just_added_table.setSortingEnabled(__sortingEnabled)
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is what I have so far for the add inventory screen. It\'s not perfect, and I\'ll probably do some rearranging/resizing of stuff to make it look better. The top half is fully editable at all times. The bottom left will remain locked until a row is selected by the user. I\'m not sure if that\'s the best way to do it, so if you have any ideas, let me know. The bottom right (where this text is) is the &quot;Console&quot;, which will be spitting out information about what\'s happening internally, it\'s basically my way of getting around pop up textbox bullshit. Any input, let me know (additional buttons, formatting preferences, etc.). I never do graphical user interface work, so I won\'t be offended in the least bit if you tell me certain parts suck.</p></body></html>", None))
        self.main_menu_tabs.setTabText(self.main_menu_tabs.indexOf(self.add_inventory_tab), _translate("Form", "Add Inventory", None))
        self.main_menu_tabs.setTabText(self.main_menu_tabs.indexOf(self.search_inventory_tab), _translate("Form", "Search/Remove Inventory", None))
        self.main_menu_tabs.setTabText(self.main_menu_tabs.indexOf(self.check_out_tab), _translate("Form", "Check Out", None))
        self.main_menu_tabs.setTabText(self.main_menu_tabs.indexOf(self.history_tab), _translate("Form", "History/Generate Reports", None))

